package com.ahuggins.warehousedemo.services;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.Base64;
import java.util.Date;

import javax.crypto.SecretKey;

import org.springframework.stereotype.Service;

import com.ahuggins.warehousedemo.dtos.AdministratorDto;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwsHeader;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SigningKeyResolver;
import io.jsonwebtoken.SigningKeyResolverAdapter;
import io.jsonwebtoken.security.Keys;

/**
 * Handles JWT generation and verification for the warehouse manager project.
 */
@Service
public final class SecurityService {
    /**
     * Gets a JWT that authorizes requests to retrieve/modify a company's stored data.
     * @param admin   Admin to authorize.
     * @return  Company's JWT that expires in 1 hour.
     * @throws UnsupportedEncodingException 
     */
    public static String getJwt(AdministratorDto admin) throws Exception{
        // Build JWT
        return Jwts.builder()
            .claim("id", admin.getId())
            .claim("companyName", admin.getCompanyName())
            .setIssuedAt(Date.from(Instant.now()))
            .setExpiration(Date.from(Instant.now().plusSeconds(3600)))
            .signWith(getSigningKey())
            .compact();
    }

    /**
     * Hashes a string.
     * @param str   String to hash.
     * @return      The hashed string.
     * @throws Exception 
     */
    public static String hashString(String str) throws Exception{
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(str.getBytes("UTF-8"));
            return Base64.getEncoder().encodeToString(hash);
        } catch (Exception e) {
            throw new Exception("Failed to hash string.");
        }
    }

    /**
     * Validates that a jwt was generated by the application, and that it belongs to a given company.
     * @param jwt
     * @param companyName
     * @return
     */
    public static boolean validate(String jwt, String companyName){
        // Setup booleans
        boolean validCompany = Jwts.claims().get("companyName", String.class).equals(companyName);
        boolean validDate = Jwts.claims().getExpiration().after(Date.from(Instant.now()));
        boolean validSignature = false; // Requires more complex verification.

        try{
            Jwts.parserBuilder().setSigningKey(getSigningKey()).build().parseClaimsJws(jwt);
            validSignature = true;
        }catch(Exception e){
            return false;
        }
        
        return validCompany && validDate && validSignature;
    }

    private static SecretKey getSigningKey() throws Exception{
        // Retrieve key from env and encrypt
        byte[] key;
        try{
            key = Base64.getEncoder().encode(System.getenv("secretKey").getBytes("UTF-8"));
        }catch(Exception e){
            throw new Exception("Encryption failure.");
        }

        return Keys.hmacShaKeyFor(key);
    }
}
