spring:
    application:
        name: payments-service  # Used as the API Gateway route ID.

server:
    port: 8082

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    # How long between each heartbeat request.
    instance:
        leaseRenewalIntervalInSeconds: 30