spring:
    application:
        name: message-queue-demo
    rabbitnq:
        host: localhost
        port: 5672


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

exchange:
    fanout: payment

routing-key: key1234