# application.properties/.yml is a config file

#   can either be a .properties or .yml file, but has to be names application and be in src/main/resources
#   here you can put properties your project uses 
#       if your project changes environments - these properties will stay the same 

# you DONT actually need these things for your project - this is just an example of how this file works


spring:
    application:
        name: hello-spring-boot     # sets the name for the project
        admin:
            enabled: false          # this is the default value - enable admin privileges for your project - only change this if you know what youre doing
    config:
        name: application       # this is the default value - this sets the name for your config file - only change this if you know what youre doing
    output:
        ansi:
            enabled: ALWAYS     # lets your terminal display colors
server:
    port: 8282                      # sets the project port number - 8080 is default


#spring.application.name=hello-spring-boot
#spring.application.admin.enabled=false
#spring.config.name=application
#server.port=8282
